version: 2

jobs:
  build:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: kubernetes-maven-plugin-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Build Jshift-Kit SNAPSHOT first
          PROJECT_DIR=`basename $PWD`
          cd ..
          git clone https://github.com/jshiftio/jshift-kit.git && cd jshift-kit/ && mvn clean install -DskipTests
          cd ../$PROJECT_DIR

          # Run maven build
          mvn clean install
    - save_cache:
        key: kubernetes-maven-plugin-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
  
  sonar:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: kubernetes-maven-plugin-sonar-{{ checksum "pom.xml" }}
    - run:
        command: |
          # Build Jshift-Kit SNAPSHOT first
          PROJECT_DIR=`basename $PWD`
          cd ..
          git clone https://github.com/jshiftio/jshift-kit.git && cd jshift-kit/ && mvn clean install -DskipTests
          cd ../$PROJECT_DIR

          MAVEN_OPTS="-Xmx3000m" mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
          -Dsonar.projectKey=jshiftio_kubernetes-maven-plugin \
          -Dsonar.organization=jshiftio \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${SONARQUBE_TOKEN}
    - save_cache:
        key: kubernetes-maven-plugin-sonar-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2
                
  sonar-pr:
    machine: true
    steps:
    - checkout
    - restore_cache:
        key: jshift-sonar-pr-{{ checksum "pom.xml" }}
    - run: |
        if [ -n "${CIRCLE_PR_NUMBER}" ]; then
          # Build Jshift-Kit SNAPSHOT first
          PROJECT_DIR=`basename $PWD`
          cd ..
          git clone https://github.com/jshiftio/jshift-kit.git && cd jshift-kit/ && mvn clean install -DskipTests
          cd ../$PROJECT_DIR

          MAVEN_OPTS="-Xmx3000m" mvn -B clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar \
             -Dsonar.projectKey=jshiftio_kubernetes-maven-plugin \
             -Dsonar.organization=jshiftio \
             -Dsonar.pullrequest.key=${CIRCLE_PR_NUMBER} \
             -Dsonar.pullrequest.branch=${CIRCLE_BRANCH} \
             -Dsonar.pullrequest.base=master \
             -Dsonar.host.url=https://sonarcloud.io \
             -Dsonar.login=${SONARQUBE_TOKEN}

        else
          echo "No Sonar PR analysis as this is not a pull request"
        fi
    - save_cache:
        key: kubernetes-maven-plugin-sonar-pr-{{ checksum "pom.xml" }}
        paths:
        - ~/.m2

workflows:
  version: 2
  all:
    jobs:
    - build
    - sonar-pr
    - sonar:
        filters:
          branches:
            only: master
